CREATE DATABASE IF NOT EXISTS pricing_management CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE pricing_management;

CREATE TABLE IF NOT EXISTS rate_rows (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  pickup_date DATE NOT NULL,
  acriss_code VARCHAR(10) NOT NULL,
  day_1 DECIMAL(10,2) NOT NULL,
  day_2 DECIMAL(10,2) NOT NULL,
  day_3 DECIMAL(10,2) NOT NULL,
  day_4 DECIMAL(10,2) NOT NULL,
  day_5 DECIMAL(10,2) NOT NULL,
  day_6 DECIMAL(10,2) NOT NULL,
  day_7 DECIMAL(10,2) NOT NULL,
  day_8 DECIMAL(10,2) NOT NULL,
  day_9 DECIMAL(10,2) NOT NULL,
  day_10 DECIMAL(10,2) NOT NULL,
  day_11 DECIMAL(10,2) NOT NULL,
  day_12 DECIMAL(10,2) NOT NULL,
  day_13 DECIMAL(10,2) NOT NULL,
  day_14 DECIMAL(10,2) NOT NULL,
  day_15 DECIMAL(10,2) NOT NULL,
  day_16 DECIMAL(10,2) NOT NULL,
  is_locked TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_rate_rows_month_code (pickup_date, acriss_code)
);

CREATE TABLE IF NOT EXISTS rate_history (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  action VARCHAR(120) NOT NULL,
  details VARCHAR(255) NULL,
  context_payload JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
